menu section is ready for check
myloserdova/mimino-bl-11 pull request #35
Opened 2022-12-02 20:09 UTC by lyubovroman

2022-12-03 07:47 UTC, VasilenkoYurii commented on src/partials/menu.html
> +    <h1 class="menu__title">МЕНЮ РЕСТОРАНУ</h1>
Нужно написать эту строку "Меню ресторану", после чего в стилях для класса добавить text-transform: uppercase;

2022-12-03 08:02 UTC, VasilenkoYurii commented on src/partials/menu.html
> +    <h1 class="menu__title">МЕНЮ РЕСТОРАНУ</h1>
Так же тут будет не h1, а h2

2022-12-03 08:04 UTC, VasilenkoYurii requested changes
Нужно поменять оглавлении секции, изменить название с больших букв, на маленькие с первой заглавной, поменять тег h1 на h2, а так же удалить файлы CSSЮ которые добавились после включения Watch Sass

2022-12-03 21:07 UTC, lyubovroman commented
а что надо исправить в названии секции?

сб, 3 дек. 2022 г. в 09:47, VasilenkoYurii ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/partials/menu.html
> <https://github.com/myloserdova/mimino-bl-11/pull/35#discussion_r1038745639>
> :
>
> > @@ -0,0 +1,247 @@
>
> +<section class="menu">
>
> +  <div class="container menu__container">
>
> +    <h1 class="menu__title">МЕНЮ РЕСТОРАНУ</h1>
>
>
> Нужно написать эту строку "Меню ресторану", после чего в стилях для класса
> добавить text-transform: uppercase;
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/myloserdova/mimino-bl-11/pull/35#pullrequestreview-1203438240>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A27F6YF57SJAWQXW3PKU4M3WLL3JDANCNFSM6AAAAAASSIGOWM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-04 08:09 UTC, addaviktory approved these changes
Все чудово

2022-12-05 07:47 UTC, VasilenkoYurii approved these changes

2022-12-05 09:14 UTC, closed without merging

2022-12-05 09:14 UTC, myloserdova commented
new branch